#!/usr/bin/python



import libxml2
import sys
import readline

doc = libxml2.newDoc("1.0")

provider_credentials = doc.newChild(None, "provider_credentials", None)

ec2_credentials = provider_credentials.newChild(None, "ec2_credentials", None)

account_number = raw_input("Account number: ")
access_key = raw_input("Access key: ")
secret_access_key = raw_input("Secret access key: ")

account_number_node = ec2_credentials.newChild(None, "account_number", account_number)
access_key = ec2_credentials.newChild(None, "access_key", access_key)
secret_access_key = ec2_credentials.newChild(None, "secret_access_key", secret_access_key)

print "The following files can be omitted if you do not intend to build S3 based images."
print "If this is the case, just hit enter for both of these questions."

certificate_file = raw_input("Certificate file: ")
key_file = raw_input("Key file: ")

if len(certificate_file) > 0:
    x509_public = open(certificate_file).read().rstrip()
else:
    x509_public = ""

if len(key_file) > 0:
    x509_private = open(key_file).read().rstrip()
else:
    x509_private = ""

certificate_node = ec2_credentials.newChild(None, "certificate", x509_public)
key_node = ec2_credentials.newChild(None, "key", x509_private)

f = open("ec2_credentials.xml", "w")
f.write(str(doc))
f.close()

print "Credentials saved in 'ec2_credentials.xml'"
